# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'AFNetworking', '~> 3.0'
pod 'SDWebImage', '~>3.8'

target 'MyntraGame' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyntraGame

  target 'MyntraGameTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyntraGameUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
