# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'SwiftKeychainWrapper'
pod 'SwiftyJSON'
pod 'ReachabilitySwift'
pod 'SDWebImage', '~>3.8'

target 'Shopping Cart' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Shopping Cart

  target 'Shopping CartTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Shopping CartUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
