# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SamsungPOC' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SamsungPOC
  	pod 'Alamofire', '~> 4.4'
    	pod 'AlamofireImage', '~> 3.1'
 	pod 'SwiftyJSON'

  target 'SamsungPOCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SamsungPOCUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
